import { Inter } from "next/font/google";
import "./globals.css";
import "./responsive.css";
import Footer from "@/components/footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SessionWrapper from "@/components/sessionWrapper";
import Navbar from "@/components/navabar";
import HandelNavBar from "@/components/handelNavbar";

export const metadata = {
  title: "JTC India",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
      <HandelNavBar>
      <Navbar />
      </HandelNavBar>
        {children}
       <HandelNavBar>
       <Footer />
       </HandelNavBar>
        </body>
    </html>

    </SessionWrapper>
  );
}
